FROM golang:1.24-alpine

RUN apk add --no-cache gcc musl-dev

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "--cmd", "go run ./cmd/server", "--", "--log-level", "debug"]
